trigger:
- master

stages:

- stage: Build

  jobs:

  - job: BuildJob

    pool:
      vmImage: ubuntu-latest

    steps:

    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package'

    - task: CopyFiles@2
      inputs:
        Contents: '**/*.war'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'warfile'

- stage: Deploy

  dependsOn: Build

  jobs:

  - deployment: DeployToTomcat

    environment: production

    strategy:
      runOnce:
        deploy:
          steps:

          - script: |
              echo "Current User:"
              whoami

              echo "Hostname:"
              hostname

              echo "Current Directory:"
              pwd

              echo "Tomcat Check:"
              ls -ld /opt/tomcat || echo "Tomcat Not Found"

            displayName: Verify Deployment Target