trigger: none

stages:

- stage: Deploy

  jobs:

  - deployment: TestEnvironment

    environment: production

    strategy:
      runOnce:
        deploy:

          steps:

          - script: |
              echo "Deployment reached VM successfully"
              whoami
              hostname
              pwd
              ls -ld /opt/tomcat

            displayName: Test Environment